- hosts: debian
  become: yes
  tasks:
    - name: Hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold
    - name: Hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
    - name: Update repos and packages
      apt:
        upgrade: yes
        update_cache: yes
- hosts: void
  become: yes
  tasks: 
    - name: Update repos and packages
      xbps:
        upgrade: yes
        update_cache: yes
- hosts: arch
  become: yes
  tasks:
    - name: Update repos and packages
      pacman:
        upgrade: yes
        update_cache: yes
